### ISSUE TITLE
New version for the docker-compose

### ISSUE THREAD

**Issue by WassimBenzarti** [yosrReact/node-api#2]
```
version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongodb:27017/test
```

The URL that you should use in the API code is
```
mongodb://mongodb:27017/test
```
